### PR TITLE
Fix namespaces.

### PR DESCRIPTION
**Pull request by jeffreyvr**
Adding a composer post install script to fix namespaces in vendor/symfony/var-dumper/Cloner/AbstractCloner.php.
 
Fixing https://github.com/spatie/wordpress-ray/issues/24

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by szepeviktor** [comment]
Why don't you simply use mozart for prefixing namespace?

**Comment by freekmurze** [comment]
@szepeviktor Because I simply don't know Mozart (I'm not into WordPress). If this can be fixed in a a simpler way, feel free to create a PR that fixes the problem.

**Comment by szepeviktor** [comment]
I manage WordPress installations with Composer, so I don't know Mozart :)

**Pull request merged**
