### PR TITLE
Keep only non-dev packages in repo

### PR DESCRIPTION
**Pull request by szepeviktor**
It makes releases much smaller.

### CODE REVIEW

**Comment by szepeviktor** [comment]
kép

This is an interesting piece of change in the lock file.
I've simply issued `composer update --no-dev` (Composer v2)

**Comment by jeffreyvr** [comment]
Just a quick note: The composer post install script has not been executed in this pull request, which leads to a couple of namespaces not being properly prefixed in vendor/symfony/var-dumper/Cloner/AbstractCloner.php.

**Comment by szepeviktor** [comment]
Thank you.

`rm -rf vendor/ && composer install` gives me
```
Generated optimized autoload files containing 1466 classes
> sed -i '' 's/'\''Symfony/'\''Spatie\\WordPressRay\\Symfony/g' ./vendor/symfony/var-dumper/Cloner/AbstractCloner.php
sed: can't read s/'Symfony/'Spatie\\WordPressRay\\Symfony/g: No such file or directory
Script sed -i '' 's/'\''Symfony/'\''Spatie\\WordPressRay\\Symfony/g' ./vendor/symfony/var-dumper/Cloner/AbstractCloner.php handling the post-install-cmd event returned with error code 2
```

**Comment by freekmurze** [comment]
I'll merge this in, and run composer again for to get the lowest version of dips

**Comment by freekmurze** [comment]
@szepeviktor @jeffreyvr I've prepared v1.2.1 on the master branch. It has not been released yet.

Could you both check if the current master is ok?

If followed these steps to prepare it: https://github.com/spatie/wordpress-ray#release-instructions-for-maintainers

**Comment by jeffreyvr** [comment]
Did a quick test, everything seems to be working.

**Pull request merged**
