### PR TITLE
Improve readme.txt to better support WordPress.org

### PR DESCRIPTION
**Pull request by slaFFik**

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by slaFFik** [comment]
@freekmurze but please don't forget to release these changes so they could take effect :)

**Comment by freekmurze** [comment]
On it!

**Comment by freekmurze** [comment]
Do you perhaps know how this icon can be set?

image

**Comment by slaFFik** [comment]
@freekmurze yes, sure.
Create a `icon-256x256.png` or `.svg` icon in `assets/` directory of the SVN repo.
Also `icon-128x128.png`. They are displayed depending on the resolution.

You can also set `banner-1544x500.png` and `banner-772x250.png` in that same directory.

Check this plugin, for example, to see how the banner will look like (At the top of the page above you plugin name and description): https://wordpress.org/plugins/woocommerce/

**Pull request merged**
